---
- name: download and install elastic GPG key
  ansible.builtin.rpm_key:
    state=present
    key=https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: create repo for elastic packages
  ansible.builtin.yum_repository:
    name: elasticsearch
    description: Elastic 8.x Repo
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    gpgcheck: yes

- name: Enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
  notify: firewall

- name: Flush handlers
  meta: flush_handlers
...
