---
ssl_certs_country: "US"
ssl_certs_locality: "Seattle"
ssl_certs_organization: "N/A"
ssl_certs_state: "Washington"
ssl_certs_common_name: "{{ ansible_hostname }}"
ssl_certs_days: "365"
ssl_certs_fields: "/C={{ssl_certs_country}}/ST={{ssl_certs_state}}/L={{ssl_certs_locality}}/O={{ssl_certs_organization}}/CN={{ssl_certs_common_name}}"

ssl_certs_path: "/etc/elasticsearch/certs"
ssl_certs_path_owner: "root"
ssl_certs_path_group: "elastic"
ssl_certs_privkey_path: "{{ssl_certs_path}}/private/{{ssl_certs_common_name}}.key"
ssl_certs_cert_path: "{{ssl_certs_path}}/{{ssl_certs_common_name}}.pem"
ssl_certs_csr_path: "{{ssl_certs_path}}/{{ssl_certs_common_name}}.csr"
ssl_certs_dhparam_path: "{{ssl_certs_path}}/dhparam.pem"
ssl_certs_mode: "0700"
ssl_certs_force_replace: yes

ssl_certs_local_privkey_path: "{{inventory_dir|default(playbook_dir)}}/files/ssl/{{ssl_certs_common_name}}.key"
ssl_certs_local_cert_path: "{{inventory_dir|default(playbook_dir)}}/files/ssl/{{ssl_certs_common_name}}.pem"
ssl_certs_local_privkey_data: ""
ssl_certs_local_cert_data: ""

ssl_certs_generate_self_signed: true
ssl_certs_key_size: "2048"
ssl_certs_generate_dh_param: false
ssl_certs_dhparam_size: "2048"
